### ISSUE TITLE
vectorForm of xi~dot~grad[div[u]] where u and xi are vectors

### ISSUE THREAD

**Issue by ymma98** [jonosquire/VEST#3]
Thanks to the author, VEST looks to be a really good package for vector analysis. I am new to Mathematica and vector analysis, and I have a question about the `vectorForm` function in VEST.
The example problem has the form shown in the figure below. The $\vec{\xi} \cdot \nabla (\nabla \cdot \vec{u})$ seemingly cannot show in the correct vector form, and thus if this expression is a part of a long expression I may not be able to use the powerful `FullSimplifyVectorForm` function.
<img src="https://user-images.githubusercontent.com/53188889/230705158-365fc4e9-f98d-4022-a40a-5ad185d99b7d.png" width="600" height="500" />

**Comment by jonosquire** [comment]
The vectorForm function is purely for presentation purposes – it won’t make any difference to later use of simplification functions (and should not be applied until the end of a calculation anyway).

The reason it hasn’t shown your expression here is that vectorForm doesn’t bother with second derivatives because vector notation becomes ambiguous and less useful for second and higher derivatives.

Jono


On 8/04/2023, at 5:43 PM, garnet ***@***.***> wrote:



Thanks to the author, VEST looks to be a really good package for vector analysis. I am new to Mathematica and vector analysis, and I have a question about the vectorForm function in VEST.
The example problem has the form shown in the figure below. The $\vec{\xi} \cdot \nabla (\nabla \cdot \vec{u})$ seemingly cannot show in the correct vector form, and thus if this expression is a part of a long expression I may not be able to use the powerful FullSimplifyVectorForm function.
[https://user-images.githubusercontent.com/53188889/230705158-365fc4e9-f98d-4022-a40a-5ad185d99b7d.png]
